"""Updated User model

Revision ID: 46b6362f3f7d
Revises: 7469ca762ac3
Create Date: 2025-06-05 20:09:04.162790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b6362f3f7d'
down_revision = '7469ca762ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'client_id')
    # ### end Alembic commands ###
