"""Add business_type and telephone to User model

Revision ID: 7469ca762ac3
Revises: c4436476e388
Create Date: 2025-06-04 23:41:23.473137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7469ca762ac3'
down_revision = 'c4436476e388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telephone', sa.String(length=50), nullable=True))
    op.drop_constraint('user_client_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_client_id_fkey', 'user', 'clients', ['client_id'], ['id'])
    op.drop_column('user', 'telephone')
    # ### end Alembic commands ###
