"""Remove duplicate client_id

Revision ID: 76ab0cff34ee
Revises: 46b6362f3f7d
Create Date: 2025-06-05 20:32:34.918238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ab0cff34ee'
down_revision = '46b6362f3f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_client_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_client_id_fkey', 'user', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
