"""Add work order status and contractor

Revision ID: 84f3221fbb2f
Revises: c29bb2925ccf
Create Date: 2025-05-15 20:52:04.728352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f3221fbb2f'
down_revision = 'c29bb2925ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        # Do not drop unnamed constraints
        batch_op.create_foreign_key('fk_work_order_contractor_id', 'user', ['contractor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_work_order_contractor_id', type_='foreignkey')
    # ### end Alembic commands ###
