"""Fix user foreign key reference

Revision ID: c4436476e388
Revises: 
Create Date: 2025-06-04 17:53:42.597247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4436476e388'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('assigned_pm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'user', ['assigned_pm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'assigned_pm_id')
    op.drop_column('clients', 'country')
    # ### end Alembic commands ###
