"""Add business_type field to WorkOrder

Revision ID: c9117ace3a75
Revises: 84f3221fbb2f
Create Date: 2025-05-24 15:26:16.109956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9117ace3a75'
down_revision = '84f3221fbb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preferred_contractor_id', sa.Integer(), nullable=True))

        batch_op.alter_column('completion_photo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('occupant_apartment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('occupant_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('rejected_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=500),
               existing_nullable=True)

        batch_op.create_foreign_key('fk_preferred_contractor_id_user', 'user', ['preferred_contractor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_preferred_contractor_id_user', type_='foreignkey')
        batch_op.drop_column('preferred_contractor_id')
        batch_op.drop_column('business_type')

        batch_op.alter_column('rejected_by',
               existing_type=sa.String(length=500),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('occupant_phone',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('occupant_apartment',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('completion_photo',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###

