"""Add due_date to WorkOrder

Revision ID: ee40da98d0c0
Revises: 76ab0cff34ee
Create Date: 2025-06-07 01:59:18.826175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee40da98d0c0'
down_revision = '76ab0cff34ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order', 'due_date')
    # ### end Alembic commands ###
