"""Fix occupant_name column

Revision ID: ef61a3b6f232
Revises: c9117ace3a75
Create Date: 2025-05-25 12:42:11.711356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef61a3b6f232'
down_revision = 'c9117ace3a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        # batch_op.drop_constraint('fk_contractor_user', type_='foreignkey')
        batch_op.drop_column('occupant_contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupant_contact', sa.VARCHAR(length=120), nullable=True))
        batch_op.create_foreign_key(None, 'contractor', ['contractor_id'], ['id'])

    # ### end Alembic commands ###
